name: My first Github Workflow
on: [push]
jobs:
  Job1:
    runs-on: ubuntu-latest 
    steps:
      - run: "docker --version"
      - run: "python --version"
  Job2:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: "pip install pylint"
      - run: "pylint app.py"
  Job3:
    runs-on: ubuntu-latest
      steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: "docker build --tag test-flask-app ."
      

